"use client";

import { FormEvent, useState } from "react";
import { History, MinusCircle, PlusCircle, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { formatDateTime, rupiah, stockStatus } from "@/lib/format";
import type { Product, StockMovement } from "@/lib/types";

type Operation = { type: "add" | "adjust"; product: Product } | null;
const movementLabels: Record<StockMovement["movement_type"], string> = { sale:"Penjualan",stock_in:"Stok masuk",adjustment_in:"Penyesuaian +",adjustment_out:"Penyesuaian −",return:"Pengembalian void",initial:"Stok awal" };

export function InventoryManager({ products, movements, canManage }: { products: Product[]; movements: StockMovement[]; canManage: boolean }) {
  const router=useRouter(); const [operation,setOperation]=useState<Operation>(null);const [pending,setPending]=useState(false);const [error,setError]=useState("");const [updateHpp,setUpdateHpp]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!operation)return;setPending(true);setError("");const form=new FormData(event.currentTarget);const supabase=createClient();
    const result=operation.type==="add"?await supabase.rpc("add_stock",{p_product_id:operation.product.id,p_quantity:Number(form.get("quantity")),p_note:String(form.get("note")||"")||null,p_unit_cost:String(form.get("unit_cost")||"")?Number(form.get("unit_cost")):null,p_update_hpp:updateHpp}):await supabase.rpc("adjust_stock",{p_product_id:operation.product.id,p_quantity_change:Number(form.get("quantity_change")),p_reason:String(form.get("reason"))});
    if(result.error){setError(result.error.message);setPending(false);return;}setOperation(null);setPending(false);setUpdateHpp(false);router.refresh();}
  return <>
    <div className="card list">{products.map(product=>{const status=stockStatus(product.stock_quantity,product.low_stock_threshold);return <div className="list-item" key={product.id}><div className="list-main"><div className="list-title">{product.name}</div><div className="list-meta">Batas minimum {product.low_stock_threshold} · {product.hpp===null?"HPP belum diatur":`HPP ${rupiah(product.hpp)}`}</div><div style={{marginTop:7}}><span className={`badge ${status.tone}`}>{status.label}</span></div></div><div><div className="list-value" style={{fontSize:22}}>{product.stock_quantity}</div><div className="tiny" style={{textAlign:"right"}}>unit</div>{canManage&&<div className="form-actions" style={{marginTop:8,gap:5}}><button className="btn icon-btn btn-secondary" onClick={()=>setOperation({type:"add",product})} title="Tambah stok"><PlusCircle size={19}/></button><button className="btn icon-btn btn-secondary" onClick={()=>setOperation({type:"adjust",product})} title="Penyesuaian"><MinusCircle size={19}/></button></div>}</div></div>})}</div>
    {canManage&&<section className="section"><div className="section-head"><h2>Riwayat Pergerakan</h2><span className="tiny">50 terbaru</span></div><div className="card list">{movements.map(movement=><div className="list-item" key={movement.id}><div className="list-main"><div className="list-title">{movement.products?.name}</div><div className="list-meta">{movementLabels[movement.movement_type]} · {formatDateTime(movement.created_at)}</div><div className="tiny">{movement.reference_note||"Tanpa catatan"} · oleh {movement.profiles?.full_name||"-"}</div></div><div className="list-value" style={{color:movement.quantity_change>0?"var(--success)":"var(--danger)"}}>{movement.quantity_change>0?"+":""}{movement.quantity_change}<div className="tiny">{movement.stock_before} → {movement.stock_after}</div></div></div>)}{!movements.length&&<div className="empty"><History/><p>Belum ada pergerakan stok.</p></div>}</div></section>}
    {operation&&<div className="sheet-backdrop"><form className="sheet form-grid" onSubmit={submit}><div className="sheet-handle"/><div className="sheet-head"><div><p className="eyebrow">{operation.type==="add"?"Stok Masuk":"Koreksi Stok"}</p><h2>{operation.product.name}</h2><p className="subtle">Stok saat ini: {operation.product.stock_quantity} unit</p></div><button type="button" className="btn icon-btn" onClick={()=>setOperation(null)}><X/></button></div>
      {error&&<div className="error">{error}</div>}{operation.type==="add"?<><div className="field"><label htmlFor="quantity">Jumlah masuk</label><input id="quantity" name="quantity" className="input" type="number" min="1" required autoFocus/></div><div className="field"><label htmlFor="unit_cost">Biaya per unit (opsional)</label><input id="unit_cost" name="unit_cost" className="input" type="number" min="0"/><label style={{display:"flex",gap:8,alignItems:"center",fontWeight:600}}><input type="checkbox" checked={updateHpp} onChange={e=>setUpdateHpp(e.target.checked)}/> Perbarui HPP produk dengan biaya ini</label></div><div className="field"><label htmlFor="note">Supplier / sumber / catatan</label><textarea id="note" name="note" className="textarea"/></div></>:<><div className="field"><label htmlFor="quantity_change">Perubahan jumlah</label><input id="quantity_change" name="quantity_change" className="input" type="number" required placeholder="Contoh: -2 atau 3"/><span className="help">Gunakan minus untuk mengurangi stok.</span></div><div className="field"><label htmlFor="reason">Alasan (wajib)</label><textarea id="reason" name="reason" className="textarea" required minLength={3} placeholder="Rusak, sampel, koreksi hitung..."/></div></>}
      <button className="btn btn-primary btn-wide btn-lg" disabled={pending}>{pending?"Menyimpan...":"Simpan Pergerakan"}</button>
    </form></div>}
  </>;
}
